version: "3.9"
services:
  agromart_db_service:
    container_name: dicionario_agromart_db_container
    image: postgres:14
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  agromart_node_service:
    container_name: dicionario_agromart_node_container
    build:
      context: .
      dockerfile: Dockerfile.node
    env_file: .env
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - DEFAULT_MAIL_SENDER=${DEFAULT_MAIL_SENDER}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - agromart_db_service

volumes:
  pgdata:
    driver: local
